languageCode: "en-us"
baseUrl: "https://chrismea.de"
title: "Chris Meade"
theme: "anubis"
paginate: 10
disqusShortname: "chris-meade"
googleAnalytics: UA-123-45
enableRobotsTXT: true
canonifyURLs: true

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about-us/
    weight: 0
  - identifier: posts
    name: Posts
    title: Posts
    url: /posts/
    weight: 0
  - identifier: LinkedIn
    name: LinkedIn
    title: LinkedIn
    url: https://linkedin.com/in/ctmeade
    weight: 0

params:
  author: "Chris Meade"
  description: "A collection of notes and tidbits"
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "static" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown